### ISSUE TITLE
Question about parsing the md on `:::`

### ISSUE THREAD

**Issue by boulderob** [Snippetors/snippets#46]
Quick question.  I would like to create a different type of markdown-it plugin that would use a "token" similar to the way `:::` is used to delineate tabs here in the markdown source.  I thought I would use your code as an example but I can't find anywhere in  the code itself that searces for the tokens `:::`!?  Where in the code is the md block parsed on `:::`?  

Thanks

**Comment by LucienZhang** [comment]
@boulderob from [here](https://github.com/Snippetors/snippets/blob/9ca8dc6582d3e0ad67dc720880b1ea871f0f2b77/packages/%40snippetors/vuepress-plugin-tabs/lib/markdownItPlugin.js#L1) it requires [markdown-it-container](https://www.npmjs.com/package/markdown-it-container)

**Comment by boulderob** [comment]
Late reply.  Thanks for the answer!  It helped.
