### ISSUE TITLE
[vuepress-plugin-code-copy] Build error at vuepress 2.0.0-beta.33

### ISSUE THREAD

**Issue by roktas** [Snippetors/snippets#47]
I'm getting a build error while issuing `vuepress build docs` command.   (No problem if I remove `vuepress-plugin-code-copy` plugin, hence this report.)  Vuepress is at version 2.0.0-beta.33.

![image](https://user-images.githubusercontent.com/47842/149421848-32f3c022-aa34-4f3b-a641-38653d1ee65c.png)

**Comment by LucienZhang** [comment]
@roktas I'm using webpack and did test it on vite. I will check, thanks for reporting

**Comment by LucienZhang** [comment]
fixed in v1.1.1
@roktas please try use the latest version

**Comment by roktas** [comment]
Hi @LucienZhang, I confirm that it works.  Thanks for your efforts, much appreciated.
