### ISSUE TITLE
vuepress-plugin-code-copy Plugin throws console errors

### ISSUE THREAD

**Issue by dan-r95** [Snippetors/snippets#49]
On the [documentation page](https://snippetors.github.io/plugins/vuepress-plugin-code-copy.html), the error console is full of 
```
Unchecked runtime.lastError: The message port closed before a response was received.
```
Also, sometimes the copy button does not show up there. Just try to refresh a couple times and the button will be gone sometime.

**Comment by LucienZhang** [comment]
@dan-r95 I checked the page again and didn't find any error from the console. seems it's caused by some extention of your browser
https://stackoverflow.com/a/54614440
