### ISSUE TITLE
Icon doesn't show when enter new page via router and hover on the block

### ISSUE THREAD

**Issue by LucienZhang** [Snippetors/snippets#52]
Dynamic icon shows when fresh the page, but doesn't show on new paged entered via router

**Comment by Mister-Hope** [comment]
Please fix this, as you should be provide a delay option or some similar thing, the default theme switch animation is greater then 100ms.

@Snippetors I will remove your plugin from awesome list if this is still not fixed in 2022/6/22. `vuepress-plugin-copy-code2` could be a demo.

**Comment by LucienZhang** [comment]
@Mister-Hope Thank you for reminding, and we noticed that we need to refactor the plugins for the breaking changes introduced in [2.0.0-beta.40](https://github.com/vuepress/vuepress-next/compare/v2.0.0-beta.39...v2.0.0-beta.40). It may take some time but we will try our best to fix it in time.

**Comment by Mister-Hope** [comment]
It's not related to the breaking changes, your plugin is not working in lower versions of vuepress. Themes may have a switch animation, so you should delay your `querySeletor` after the dom is changed, so you will need a delay option.

**Comment by LucienZhang** [comment]
@Mister-Hope thank you for your explanation. Yes, I was just wondering if I should also refactor the plugins with the fix to fit the latest breaking changes, or just have the dependency to vuepress fixed to `2.0.0-beta.25` for now.
So let me fix the bug first, then I will refactor the plugins a little bit in another PR to catch the latest version of vuepess.

**Comment by LucienZhang** [comment]
@Mister-Hope The bug has been fixed in #57 , and the new version [1.1.3](https://www.npmjs.com/package/@snippetors/vuepress-plugin-code-copy) has been released, please take a look when you have time
